[package]
name = "scene-parser"
version = "0.1.0"
edition = "2021"
build = "src/build.rs"

[dependencies]
lalrpop-util = { version = "0.19.12", features = ["lexer"] }
raytrace-lib = { path = "../raytrace-lib/" }

[build-dependencies]
lalrpop = "0.19.12"

